### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [40ants/commondoc-markdown#1]
Building with SBCL 2.1.7.62-417920f09 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 2ba30c9478ca0cc84424f74b8f41d19ed8dab963

*commondoc-markdown-test* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BF8103}>: Component "common-doc.ops" not found, required by #<PACKAGE-INFERRED-SYSTEM "commondoc-markdown-test/core">

```

[Full log here](http://report.quicklisp.org/2021-09-14/failure-report/commondoc-markdown.html)

**Comment by svetlyak40wt** [comment]
Fixed in https://github.com/40ants/commondoc-markdown/commit/37a2169eb71e8d2da245a8bf00f6bf15945e70ac
